/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ftpClient;
 
import java.io.IOException;

/**
 *
 * @author gdufs
 */
public class FileClientJFrame extends javax.swing.JFrame {

    private FileDialogClient ec;
    private FileDataClient file;

    /**
     * Creates new form IOJFrame
     */
    public FileClientJFrame() {
        initComponents();
        ec = null;
        file = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_showinfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_showinfo = new javax.swing.JTextArea();
        jLabel_input = new javax.swing.JLabel();
        jTextField_input = new javax.swing.JTextField();
        jButton_send = new javax.swing.JButton();
        jButton_quit = new javax.swing.JButton();
        jLabel_IPAddress = new javax.swing.JLabel();
        jTextField_IPAddress = new javax.swing.JTextField();
        jLabel_port = new javax.swing.JLabel();
        jTextField_port = new javax.swing.JTextField();
        jButton_connect = new javax.swing.JButton();
        jButton_upload = new javax.swing.JButton();
        jButton_download = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel_showinfo.setText("显示面板：");

        jTextArea_showinfo.setEditable(false);
        jTextArea_showinfo.setBackground(new java.awt.Color(255, 255, 0));
        jTextArea_showinfo.setColumns(20);
        jTextArea_showinfo.setRows(5);
        jScrollPane1.setViewportView(jTextArea_showinfo);

        jLabel_input.setText("输入框：");

        jTextField_input.setBackground(new java.awt.Color(0, 255, 255));
        jTextField_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_inputActionPerformed(evt);
            }
        });
        jTextField_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_inputKeyPressed(evt);
            }
        });

        jButton_send.setText("发送");
        jButton_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sendActionPerformed(evt);
            }
        });
        jButton_send.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_sendKeyPressed(evt);
            }
        });

        jButton_quit.setText("退出");
        jButton_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_quitActionPerformed(evt);
            }
        });

        jLabel_IPAddress.setText("IP地址：");

        jTextField_IPAddress.setText("192.168.221.74");
        jTextField_IPAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IPAddressActionPerformed(evt);
            }
        });

        jLabel_port.setText("端口：");

        jTextField_port.setText("8081");
        jTextField_port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_portActionPerformed(evt);
            }
        });

        jButton_connect.setText("连接");
        jButton_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_connectActionPerformed(evt);
            }
        });
        jButton_connect.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_connectKeyPressed(evt);
            }
        });

        jButton_upload.setText("上传");

        jButton_download.setText("下载");
        jButton_download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_downloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_input, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_showinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_IPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_IPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_port)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_port, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jButton_connect))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                            .addComponent(jTextField_input))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_upload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_quit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_download, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_IPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_IPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_port)
                    .addComponent(jTextField_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_connect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_showinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_input, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_upload)
                    .addComponent(jButton_download))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_send)
                    .addComponent(jButton_quit))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_quitActionPerformed
        // TODO add your handling code here:
        if (ec != null) {
            ec.close();
        }
        System.exit(0);
    }//GEN-LAST:event_jButton_quitActionPerformed

    private void jButton_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sendActionPerformed
        // TODO add your handling code here:
        String msgSend = this.jTextField_input.getText();
        this.jTextField_input.setText(null);

        try {
            ec.send(msgSend);
        } catch (IOException ex) {
            this.jTextArea_showinfo.append("Echo: 对话出错终止");
        }
    }//GEN-LAST:event_jButton_sendActionPerformed

    private void jTextField_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_inputActionPerformed
        // TODO add your handling code here:
        this.jButton_sendActionPerformed(evt);
    }//GEN-LAST:event_jTextField_inputActionPerformed

    private void jTextField_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_inputKeyPressed
        // TODO add your handling code here:
        if (evt.isAltDown()) {
            this.jButton_sendActionPerformed(null);
        }
    }//GEN-LAST:event_jTextField_inputKeyPressed

    private void jTextField_IPAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IPAddressActionPerformed
        // TODO add your handling code here:
        this.jTextField_portActionPerformed(evt);
    }//GEN-LAST:event_jTextField_IPAddressActionPerformed

    private void jTextField_portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_portActionPerformed
        // TODO add your handling code here:
        if(this.jTextField_IPAddress.getText() != null && this.jTextField_port.getText() != null) {
            this.jButton_connectActionPerformed(evt);
        }
    }//GEN-LAST:event_jTextField_portActionPerformed

    private void jButton_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_connectActionPerformed
        // TODO add your handling code here:
        String ip = this.jTextField_IPAddress.getText();
        String port = this.jTextField_port.getText();
        try {
            this.ec = new FileDialogClient(ip, port);
            this.file = new FileDataClient(ip, port);
            
            this.jTextArea_showinfo.append("服务器连接成功.\r\n");
        } catch (IOException ex) {
            this.jTextArea_showinfo.append("服务器 FileDialogClient 连接失败.\r\n");
        }

        Thread re = new Thread() {
            @Override
            public void run() {
                String msg = null;
                while (true) {
                    try {
                        msg = ec.receive();
                        if (msg != null) {
                            jTextArea_showinfo.append("Echo : " + msg + "\r\n");
                        }
                    } catch (IOException ex) {
                        jTextArea_showinfo.append("异常关闭");
                        break;
                    }
                }
            }
        };
        re.start();
        
        this.jTextField_input.setText("20131003615 林明明");
    }//GEN-LAST:event_jButton_connectActionPerformed

    private void jButton_connectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_connectKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_connectKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jButton_sendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_sendKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_sendKeyPressed

    private void jButton_downloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_downloadActionPerformed
        try {
             this.file.fileGet(this.jTextField_input.getText());
        } catch (IOException ex) { }
    }//GEN-LAST:event_jButton_downloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
           // java.util.logging.Logger.getLogger(IOJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
           // java.util.logging.Logger.getLogger(IOJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
           // java.util.logging.Logger.getLogger(IOJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           // java.util.logging.Logger.getLogger(IOJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileClientJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_connect;
    private javax.swing.JButton jButton_download;
    private javax.swing.JButton jButton_quit;
    private javax.swing.JButton jButton_send;
    private javax.swing.JButton jButton_upload;
    private javax.swing.JLabel jLabel_IPAddress;
    private javax.swing.JLabel jLabel_input;
    private javax.swing.JLabel jLabel_port;
    private javax.swing.JLabel jLabel_showinfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_showinfo;
    private javax.swing.JTextField jTextField_IPAddress;
    private javax.swing.JTextField jTextField_input;
    private javax.swing.JTextField jTextField_port;
    // End of variables declaration//GEN-END:variables
}
